version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-

      - run:
          name: Node dependencies
          command: sudo npm install -g firebase-tools

      - save_cache:
          paths:
            - /usr/local/bundle
            - /usr/local/lib/node_modules

      - run:
          name: Deploy
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive
