version: 2
jobs:
  build:
    filters:
        branches:
            only: master
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Node dependencies
          command: sudo npm install -g firebase-tools
      - run:
          name: Deploy
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive
